### ISSUE TITLE
Memory safety w/concurrency

### ISSUE THREAD

**Issue by richlander** [ossf/Memory-Safety#26]
@nellshamrell shared this doc with me: https://github.com/ossf/Memory-Safety/blob/main/docs/memory-safety-continuum.md. Thanks Nell!

>  Using a memory safe by default language with developer best practices, but no automated tooling to check for memory safety

That caught my eye. From the vantage point of C# and other memory-safe languages, this doesn't really make sense. The "automated tooling" is the compiler. For Rust, it is literally the compiler. For C#, it is the compiler + analyzers (which run within the compiler). 

[Analyzers](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/overview) are a compiler extension point intended for first and third party compiler diagnostics. Also, analyzers can expose fixers so that in an IDE, a given problem may be raised with an associated gesture to fix the problem automatically.
 
For managed/memory-safe languages, the key topic ends up being the memory safety story in the face of concurrency. This is what the doc really needs to focus on to be useful, IMO. In absence of that, most memory-safe language code developers will ask for the tools that they should be running and the safety category that the tools protect/expose. It's also worth noting that this, IMO, is where Rust makes (well founded) claims that is has a superior model to other languages because its borrowing model applies equally well to concurrency. Automatic memory management brings a high level of safety, but it is unable to rise to the same level, of providing thread/task safety. That's why C#, for example, relies so heavily on analyzers to augment the safety model. Many analyzers are enabled by default.

We wrote a section on safety in a semi-recent post that gets at some of this: https://devblogs.microsoft.com/dotnet/why-dotnet/#safety. We share your conviction that this general topic is of critical importance.

**Comment by balteravishay** [comment]
Discussed this issue over the SIG meeting on July 11th and agreed to merge some of the continuum's steps to make less distinction between compiler and compiler-activated plugin, post processors etc.
@balteravishay to propose the change
