### ISSUE TITLE
Missing section Invest in Education

### ISSUE THREAD

**Issue by balteravishay** [ossf/Memory-Safety#6]
The plan's revised document is missing the Invest in Education section, marked as TO DO

**Comment by SecurityCRob** [comment]
I am glad to assist in shaping this section

**Comment by SecurityCRob** [comment]
created this to start us off:   https://github.com/ossf/Memory-Safety/pull/7

**Comment by SecurityCRob** [comment]
i can't add Nell as reviewer for some reason
@nellshamrell

**Comment by balteravishay** [comment]
this issue was addressed by #7 . closing.
